import "~/styles/globals.css";
import '@radix-ui/themes/styles.css';

import { Theme } from '@radix-ui/themes';
import { ThemeProvider as NextThemesProvider } from "next-themes"
import { type ThemeProviderProps } from "next-themes/dist/types"

import { Inter as FontSans } from "next/font/google"
import cn from 'classnames';
import { type Metadata } from "next";
import { TRPCReactProvider } from "~/trpc/react";

import NavBar from "./_components/navbar";
import { HydrateClient } from "~/trpc/server";

export function ThemeProvider({ children, ...props }: ThemeProviderProps) {
  return <NextThemesProvider {...props}>{children}</NextThemesProvider>
}

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased  overflow-auto",
          fontSans.variable
        )}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <Theme
            accentColor="mint"
            grayColor="gray"
            panelBackground="solid"
            scaling="100%"
            radius="full"
          >

          <NavBar/>

           <TRPCReactProvider>
            <HydrateClient>
            {children}
            </HydrateClient>
            
            </TRPCReactProvider>
           
           </Theme> 

          </ThemeProvider>     
      </body>
    </html>
  );
}
